#include "lou/lexer/token.h"
#include <stdio.h>

#define WRITE_TOKEN(NAME) \
    case LOU_TOKEN_##NAME: \
      fputs(#NAME, stream); \
      return; \

void lou_token_write(const lou_token_t *token, FILE *stream) {
  switch (token->kind) {
    WRITE_TOKEN(OPENING_CIRCLE_BRACE);
    WRITE_TOKEN(CLOSING_CIRCLE_BRACE);
    WRITE_TOKEN(OPENING_FIGURE_BRACE);
    WRITE_TOKEN(CLOSING_FIGURE_BRACE);
    WRITE_TOKEN(OPENING_SQUARE_BRACE);
    WRITE_TOKEN(CLOSING_SQUARE_BRACE);
    WRITE_TOKEN(COLON);
    WRITE_TOKEN(FUNCTION_RETURNS);
    WRITE_TOKEN(ASSIGN);
    WRITE_TOKEN(COMMA);
    WRITE_TOKEN(DOT);
    WRITE_TOKEN(MINUS);
    WRITE_TOKEN(FUN);
    WRITE_TOKEN(PUBLIC);
    WRITE_TOKEN(META);
    WRITE_TOKEN(CONST);
    WRITE_TOKEN(FINAL);
    WRITE_TOKEN(VAR);
    WRITE_TOKEN(RETURN);
    WRITE_TOKEN(IF);
    WRITE_TOKEN(IDENT);
    WRITE_TOKEN(STRING);
    WRITE_TOKEN(CHAR);
    WRITE_TOKEN(INTEGER);
    WRITE_TOKEN(EOI);
    WRITE_TOKEN(FAILED);
  }
  fputs("(invalid)", stream);
}

